'use client';

export type EngravingEffect = 'laser' | 'emboss' | 'neon' | 'deboss';

export interface EngravingSnapshot {
  text: string;
  fontIdx: number;
  color: string;
  size: number;
  opacity: number;
  effect: EngravingEffect;
  xPct: number;
  yPct: number;
}

export interface Product {
  id: number;
  name: string;
  brand: string;
  category: string;
  price: number;
  originalPrice: number;
  rating: number;
  reviews: number;
  emoji: string;
  badge?: 'sale' | 'new' | 'prime';
  engravable: boolean;
  img: string;
  backImg: string;
  imgs: string[];
  desc: string;
  features: string[];
  specs: Record<string, string>;
}

export interface CartItem {
  id: number;
  qty: number;
  engraving?: EngravingSnapshot;
}

export interface UserProfile {
  name: string;
  email: string;
}

export interface AIRecommendation {
  id: number;
  reason: string;
}

export interface FontOption {
  name: string;
  fontFamily: string;
  preview: string;
  letterSpacing: string;
}

export const ENGRAVE_CHARGE = 499;

export const FONTS: FontOption[] = [
  {
    name: 'Classic Serif',
    fontFamily: "'Playfair Display', Georgia, serif",
    preview: 'Arjun',
    letterSpacing: '1.5px',
  },
  {
    name: 'Bold Sans',
    fontFamily: "'Outfit', 'DM Sans', Arial, sans-serif",
    preview: 'ARJUN',
    letterSpacing: '2px',
  },
  {
    name: 'Script',
    fontFamily: "'Dancing Script', cursive",
    preview: 'Arjun',
    letterSpacing: '0px',
  },
  {
    name: 'Monospace',
    fontFamily: "'Space Mono', monospace",
    preview: 'ARJUN',
    letterSpacing: '2px',
  },
];

export const PRODUCTS: Product[] = [
  {
    id: 1,
    name: 'Apple iPhone 15 Pro Max',
    brand: 'Apple',
    category: 'Electronics',
    price: 134900,
    originalPrice: 149900,
    rating: 4.8,
    reviews: 18432,
    emoji: '📱',
    badge: 'prime',
    engravable: true,
    img: 'https://m.media-amazon.com/images/I/81Os1SDWpcL._AC_SX522_.jpg',
    backImg: 'https://m.media-amazon.com/images/I/71bVnDeSBFL._AC_SX522_.jpg',
    imgs: [
      'https://m.media-amazon.com/images/I/81Os1SDWpcL._AC_SX522_.jpg',
      'https://m.media-amazon.com/images/I/71bVnDeSBFL._AC_SX522_.jpg',
    ],
    desc: 'Experience the pinnacle of smartphone tech with the A17 Pro chip, titanium design, and a 48MP camera.',
    features: [
      'A17 Pro chip with Neural Engine',
      '48MP Main camera with 5x Optical Zoom',
      'Titanium frame',
      'All-day battery',
      'Dynamic Island',
    ],
    specs: {
      Display: '6.7" Super Retina XDR',
      Storage: '256GB',
      OS: 'iOS 17',
      Color: 'Natural Titanium',
    },
  },
  {
    id: 2,
    name: 'Apple MacBook Air M3',
    brand: 'Apple',
    category: 'Electronics',
    price: 114900,
    originalPrice: 129900,
    rating: 4.9,
    reviews: 6543,
    emoji: '💻',
    badge: 'new',
    engravable: true,
    img: 'https://m.media-amazon.com/images/I/71TPda7cwUL._AC_SX522_.jpg',
    backImg: 'https://m.media-amazon.com/images/I/61ZM0JFY7iL._AC_SX522_.jpg',
    imgs: [
      'https://m.media-amazon.com/images/I/71TPda7cwUL._AC_SX522_.jpg',
      'https://m.media-amazon.com/images/I/61ZM0JFY7iL._AC_SX522_.jpg',
    ],
    desc: "World's best consumer laptop. M3 chip with 18-hour battery. Aluminium unibody.",
    features: [
      'Apple M3 chip',
      '18-hour battery',
      '15.3" Liquid Retina display',
      'MagSafe charging',
      'Up to 24GB unified memory',
    ],
    specs: {
      Processor: 'M3',
      RAM: '8GB',
      Storage: '256GB SSD',
      Display: '15.3"',
    },
  },
  {
    id: 3,
    name: 'Apple AirPods Pro 2nd Gen',
    brand: 'Apple',
    category: 'Electronics',
    price: 24900,
    originalPrice: 26900,
    rating: 4.8,
    reviews: 34521,
    emoji: '🎵',
    badge: 'prime',
    engravable: true,
    img: 'https://m.media-amazon.com/images/I/71zny7BTRlL._AC_SX522_.jpg',
    backImg: 'https://m.media-amazon.com/images/I/71zny7BTRlL._AC_SX522_.jpg',
    imgs: ['https://m.media-amazon.com/images/I/71zny7BTRlL._AC_SX522_.jpg'],
    desc: 'Active Noise Cancellation, Adaptive Transparency, and Personalized Spatial Audio.',
    features: [
      'Active Noise Cancellation',
      'Adaptive Transparency',
      '30-hr total battery',
      'H2 chip',
      'MagSafe charging case',
    ],
    specs: {
      Battery: '30 hrs total',
      Chip: 'H2',
      'Water Resist': 'IPX4',
      Case: 'MagSafe',
    },
  },
  {
    id: 4,
    name: 'Sony WH-1000XM5 Headphones',
    brand: 'Sony',
    category: 'Electronics',
    price: 24990,
    originalPrice: 34990,
    rating: 4.7,
    reviews: 12087,
    emoji: '🎧',
    badge: 'sale',
    engravable: true,
    img: 'https://m.media-amazon.com/images/I/61eGBRsCwDL._AC_SX522_.jpg',
    backImg: 'https://m.media-amazon.com/images/I/71BmW7Bz3KL._AC_SX522_.jpg',
    imgs: [
      'https://m.media-amazon.com/images/I/61eGBRsCwDL._AC_SX522_.jpg',
      'https://m.media-amazon.com/images/I/71BmW7Bz3KL._AC_SX522_.jpg',
    ],
    desc: 'Industry-leading noise cancelling headphones with 30-hour battery.',
    features: [
      'Industry-leading ANC',
      '30-hour battery',
      'Multipoint connection',
      'Speak-to-chat',
      'Premium HD voice',
    ],
    specs: {
      Type: 'Over-ear',
      Battery: '30 hrs',
      Connectivity: 'BT 5.2',
      NFC: 'Yes',
    },
  },
  {
    id: 5,
    name: 'Samsung Galaxy S24 Ultra',
    brand: 'Samsung',
    category: 'Electronics',
    price: 129999,
    originalPrice: 139999,
    rating: 4.7,
    reviews: 9654,
    emoji: '📱',
    badge: 'new',
    engravable: true,
    img: 'https://m.media-amazon.com/images/I/71IeKNjlk0L._AC_SX522_.jpg',
    backImg: 'https://m.media-amazon.com/images/I/71IeKNjlk0L._AC_SX522_.jpg',
    imgs: ['https://m.media-amazon.com/images/I/71IeKNjlk0L._AC_SX522_.jpg'],
    desc: 'Galaxy AI is here. Ultimate experience with S Pen, 200MP camera, titanium frame.',
    features: [
      '200MP main camera',
      'Built-in S Pen',
      'Galaxy AI',
      'Titanium frame',
      '5000mAh battery',
    ],
    specs: {
      Display: '6.8" QHD+ AMOLED',
      RAM: '12GB',
      Storage: '256GB',
      OS: 'Android 14',
    },
  },
  {
    id: 6,
    name: 'Canon EOS R50 Mirrorless',
    brand: 'Canon',
    category: 'Electronics',
    price: 64990,
    originalPrice: 79990,
    rating: 4.6,
    reviews: 4532,
    emoji: '📷',
    badge: 'new',
    engravable: true,
    img: 'https://m.media-amazon.com/images/I/71nT4e5OEZL._AC_SX522_.jpg',
    backImg: 'https://m.media-amazon.com/images/I/71nT4e5OEZL._AC_SX522_.jpg',
    imgs: ['https://m.media-amazon.com/images/I/71nT4e5OEZL._AC_SX522_.jpg'],
    desc: 'Perfect mirrorless for creators. 24.2MP APS-C sensor with AI subject tracking.',
    features: [
      '24.2MP APS-C sensor',
      'AI subject detection',
      '4K 30fps',
      'Flip-out touchscreen',
      'Wi-Fi & Bluetooth',
    ],
    specs: {
      Sensor: '24.2MP',
      Video: '4K 30fps',
      Screen: '3" flip',
      Weight: '375g',
    },
  },
  {
    id: 7,
    name: 'Samsung 55" 4K QLED TV',
    brand: 'Samsung',
    category: 'Electronics',
    price: 64999,
    originalPrice: 89999,
    rating: 4.6,
    reviews: 8754,
    emoji: '📺',
    badge: 'sale',
    engravable: false,
    img: 'https://m.media-amazon.com/images/I/71pnHoSLXfL._AC_SX522_.jpg',
    backImg: 'https://m.media-amazon.com/images/I/71pnHoSLXfL._AC_SX522_.jpg',
    imgs: ['https://m.media-amazon.com/images/I/71pnHoSLXfL._AC_SX522_.jpg'],
    desc: '4K QLED with Quantum Dot tech delivering 100% Color Volume.',
    features: [
      'Quantum Dot 4K',
      '120Hz refresh',
      'Dolby Atmos',
      'SmartThings Hub',
      'Alexa & Google',
    ],
    specs: {
      Resolution: '4K UHD',
      Panel: 'QLED',
      Refresh: '120Hz',
      HDR: 'HDR10+',
    },
  },
  {
    id: 8,
    name: 'boAt Airdopes 141 TWS',
    brand: 'boAt',
    category: 'Electronics',
    price: 999,
    originalPrice: 2990,
    rating: 4.2,
    reviews: 456789,
    emoji: '🎵',
    badge: 'sale',
    engravable: true,
    img: 'https://m.media-amazon.com/images/I/51DUOt6RFQL._AC_SX522_.jpg',
    backImg: 'https://m.media-amazon.com/images/I/51DUOt6RFQL._AC_SX522_.jpg',
    imgs: ['https://m.media-amazon.com/images/I/51DUOt6RFQL._AC_SX522_.jpg'],
    desc: '42-hour total playtime, IPX4 water resistance, BEAST Mode for gaming.',
    features: [
      '42-hour total playtime',
      'BEAST Mode gaming',
      'IPX4 water resistant',
      'Instant connect',
      '8mm drivers',
    ],
    specs: {
      Battery: '42 hrs',
      Driver: '8mm',
      Water: 'IPX4',
      Latency: '60ms',
    },
  },
  {
    id: 9,
    name: 'Apple iPad Pro M4',
    brand: 'Apple',
    category: 'Electronics',
    price: 109900,
    originalPrice: 119900,
    rating: 4.9,
    reviews: 7231,
    emoji: '📟',
    badge: 'new',
    engravable: true,
    img: 'https://m.media-amazon.com/images/I/71gF8Jk0XWL._AC_SX522_.jpg',
    backImg: 'https://m.media-amazon.com/images/I/81uMDMJpHQL._AC_SX522_.jpg',
    imgs: [
      'https://m.media-amazon.com/images/I/71gF8Jk0XWL._AC_SX522_.jpg',
      'https://m.media-amazon.com/images/I/81uMDMJpHQL._AC_SX522_.jpg',
    ],
    desc: 'Impossibly thin iPad with M4 chip. Brilliant 13" Ultra Retina XDR OLED display.',
    features: [
      'M4 chip',
      'Ultra Retina XDR OLED',
      'Apple Pencil Pro support',
      '10-hour battery',
      'Thunderbolt port',
    ],
    specs: {
      Display: '13" OLED',
      Processor: 'M4',
      Storage: '256GB',
      Weight: '579g',
    },
  },
  {
    id: 10,
    name: 'Nike Air Max 270',
    brand: 'Nike',
    category: 'Clothing',
    price: 10995,
    originalPrice: 13495,
    rating: 4.4,
    reviews: 5421,
    emoji: '👟',
    badge: 'sale',
    engravable: false,
    img: 'https://m.media-amazon.com/images/I/61sDJEKuZ6L._AC_UX522_.jpg',
    backImg: '',
    imgs: ['https://m.media-amazon.com/images/I/61sDJEKuZ6L._AC_UX522_.jpg'],
    desc: "Nike's biggest heel Air unit yet for a super-cushioned everyday ride.",
    features: ['Full-length Max Air', 'Mesh upper', 'Rubber outsole', 'Multiple colorways'],
    specs: {
      Material: 'Mesh/Synthetic',
      Sole: 'Rubber',
      Closure: 'Lace-up',
      Care: 'Spot clean',
    },
  },
  {
    id: 11,
    name: 'Adidas Ultraboost 22',
    brand: 'Adidas',
    category: 'Clothing',
    price: 13999,
    originalPrice: 16999,
    rating: 4.5,
    reviews: 4312,
    emoji: '🥿',
    badge: 'prime',
    engravable: false,
    img: 'https://m.media-amazon.com/images/I/41PbsxV2qNL._AC_SX522_.jpg',
    backImg: '',
    imgs: ['https://m.media-amazon.com/images/I/41PbsxV2qNL._AC_SX522_.jpg'],
    desc: 'Feel the energy return with Adidas Boost technology in every stride.',
    features: [
      'Responsive BOOST midsole',
      'Primeknit+ upper',
      'Continental rubber outsole',
      'Linear Energy Push',
      'Recycled materials',
    ],
    specs: {
      Material: 'Primeknit',
      Sole: 'Continental',
      Type: 'Running',
      Drop: '10mm',
    },
  },
  {
    id: 12,
    name: "Levi's 511 Slim Jeans",
    brand: "Levi's",
    category: 'Clothing',
    price: 2999,
    originalPrice: 3999,
    rating: 4.5,
    reviews: 18234,
    emoji: '👖',
    badge: 'sale',
    engravable: false,
    img: 'https://m.media-amazon.com/images/I/71f5Eu5lJSL._AC_SX522_.jpg',
    backImg: '',
    imgs: ['https://m.media-amazon.com/images/I/71f5Eu5lJSL._AC_SX522_.jpg'],
    desc: 'Slim fit through seat and thigh. Versatile everyday jean in classic indigo.',
    features: ['Slim fit', 'Mid rise', 'Classic 5-pocket', 'Stretch denim'],
    specs: {
      Fit: 'Slim',
      Rise: 'Mid',
      Material: '98% Cotton 2% Elastane',
      Care: 'Machine Wash',
    },
  },
  {
    id: 13,
    name: 'Zara Floral Midi Dress',
    brand: 'Zara',
    category: 'Clothing',
    price: 3990,
    originalPrice: 5990,
    rating: 4.3,
    reviews: 3421,
    emoji: '👗',
    badge: 'sale',
    engravable: false,
    img: 'https://m.media-amazon.com/images/I/61b8OmWRs6L._AC_SX522_.jpg',
    backImg: '',
    imgs: ['https://m.media-amazon.com/images/I/61b8OmWRs6L._AC_SX522_.jpg'],
    desc: 'Flowy midi dress with all-over floral print. Perfect for summer occasions.',
    features: ['Floral print', 'Midi length', 'V-neckline', 'Relaxed fit', 'Side pockets'],
    specs: {
      Material: '100% Viscose',
      Length: 'Midi',
      Fit: 'Relaxed',
      Care: 'Hand Wash',
    },
  },
  {
    id: 14,
    name: 'H&M Oversized Graphic Tee',
    brand: 'H&M',
    category: 'Clothing',
    price: 799,
    originalPrice: 1299,
    rating: 4.1,
    reviews: 6543,
    emoji: '👕',
    badge: 'new',
    engravable: false,
    img: 'https://m.media-amazon.com/images/I/71LQvLgcK5L._AC_SX522_.jpg',
    backImg: '',
    imgs: ['https://m.media-amazon.com/images/I/71LQvLgcK5L._AC_SX522_.jpg'],
    desc: 'Relaxed cotton oversized T-shirt with dropped shoulders and graphic print.',
    features: ['100% cotton jersey', 'Oversized fit', 'Graphic print', 'Dropped shoulders'],
    specs: {
      Material: '100% Cotton',
      Fit: 'Oversized',
      Care: 'Machine Wash',
      Origin: 'Bangladesh',
    },
  },
  {
    id: 15,
    name: 'Instant Pot Duo 7-in-1',
    brand: 'Instant Pot',
    category: 'Home',
    price: 5999,
    originalPrice: 8999,
    rating: 4.6,
    reviews: 23541,
    emoji: '🍲',
    badge: 'sale',
    engravable: false,
    img: 'https://m.media-amazon.com/images/I/71V1cCRXtBL._AC_SX522_.jpg',
    backImg: '',
    imgs: ['https://m.media-amazon.com/images/I/71V1cCRXtBL._AC_SX522_.jpg'],
    desc: '7-in-1: Pressure Cooker, Slow Cooker, Rice Cooker, Sauté, Steamer, Yogurt Maker.',
    features: ['7-in-1 functionality', '6 quart capacity', '13 smart programs', '70% faster cooking'],
    specs: {
      Capacity: '6 Quart',
      Wattage: '1000W',
      Programs: '13',
      Material: 'Stainless Steel',
    },
  },
  {
    id: 16,
    name: 'Dyson V15 Detect Cordless',
    brand: 'Dyson',
    category: 'Home',
    price: 52900,
    originalPrice: 62900,
    rating: 4.7,
    reviews: 9876,
    emoji: '🧹',
    badge: 'new',
    engravable: false,
    img: 'https://m.media-amazon.com/images/I/515Ht8HFTrL._AC_SX522_.jpg',
    backImg: '',
    imgs: ['https://m.media-amazon.com/images/I/515Ht8HFTrL._AC_SX522_.jpg'],
    desc: 'Laser reveals hidden dust. Piezo sensor. Most powerful Dyson yet.',
    features: ['Laser dust detection', 'Piezo particle sensor', '60-min runtime', 'HEPA filtration', 'LCD screen'],
    specs: {
      Battery: '60 min',
      Suction: '230 AW',
      Filtration: 'HEPA',
      Weight: '3.1 kg',
    },
  },
  {
    id: 17,
    name: 'Prestige Induction Cooktop',
    brand: 'Prestige',
    category: 'Home',
    price: 2199,
    originalPrice: 3500,
    rating: 4.3,
    reviews: 15432,
    emoji: '🍳',
    badge: 'sale',
    engravable: false,
    img: 'https://m.media-amazon.com/images/I/51GMOqy0oWL._AC_SX522_.jpg',
    backImg: '',
    imgs: ['https://m.media-amazon.com/images/I/51GMOqy0oWL._AC_SX522_.jpg'],
    desc: "India's most trusted brand. 2000W with 7 preset menus and feather-touch controls.",
    features: ['2000W', '7 preset menus', 'Feather-touch panel', 'Auto voltage regulator'],
    specs: {
      Power: '2000W',
      Menus: '7',
      Voltage: '220-240V',
      Color: 'Black',
    },
  },
  {
    id: 18,
    name: 'Atomic Habits',
    brand: 'James Clear',
    category: 'Books',
    price: 349,
    originalPrice: 599,
    rating: 4.9,
    reviews: 142087,
    emoji: '📗',
    badge: 'sale',
    engravable: false,
    img: 'https://m.media-amazon.com/images/I/81YkqyaFVEL._AC_SY436_FMwebp_QL65_.jpg',
    backImg: '',
    imgs: ['https://m.media-amazon.com/images/I/81YkqyaFVEL._AC_SY436_FMwebp_QL65_.jpg'],
    desc: '#1 NYT bestseller. A proven framework for improving every day.',
    features: [
      '10M+ copies sold',
      '4 laws of behavior change',
      'Practical strategies',
      'Real-world case studies',
    ],
    specs: {
      Pages: '320',
      Publisher: 'Random House',
      Language: 'English',
      Format: 'Paperback',
    },
  },
  {
    id: 19,
    name: 'The Alchemist',
    brand: 'Paulo Coelho',
    category: 'Books',
    price: 199,
    originalPrice: 399,
    rating: 4.7,
    reviews: 98765,
    emoji: '📘',
    badge: 'sale',
    engravable: false,
    img: 'https://m.media-amazon.com/images/I/71aFt4+OTOL._AC_SY436_FMwebp_QL65_.jpg',
    backImg: '',
    imgs: ['https://m.media-amazon.com/images/I/71aFt4+OTOL._AC_SY436_FMwebp_QL65_.jpg'],
    desc: 'A magical story about following your dream and listening to your heart.',
    features: ['65M+ copies sold', '30+ years bestseller', 'Translated into 80 languages'],
    specs: {
      Pages: '197',
      Publisher: 'HarperOne',
      Language: 'English',
      Format: 'Paperback',
    },
  },
  {
    id: 20,
    name: 'Liforme Premium Yoga Mat',
    brand: 'Liforme',
    category: 'Sports',
    price: 2999,
    originalPrice: 3999,
    rating: 4.6,
    reviews: 7654,
    emoji: '🧘',
    badge: 'prime',
    engravable: false,
    img: 'https://m.media-amazon.com/images/I/71gSLkbFvxL._AC_SX522_.jpg',
    backImg: '',
    imgs: ['https://m.media-amazon.com/images/I/71gSLkbFvxL._AC_SX522_.jpg'],
    desc: "World's most eco-friendly yoga mat with unique AlignForMe system.",
    features: [
      'AlignForMe system',
      'GripForMe surface',
      '175cm x 68cm',
      '4.2mm thickness',
      'Biodegradable',
    ],
    specs: {
      Size: '175 x 68 cm',
      Thickness: '4.2mm',
      Material: 'Natural Rubber',
      Weight: '2.5 kg',
    },
  },
  {
    id: 21,
    name: 'Yonex Badminton Racket',
    brand: 'Yonex',
    category: 'Sports',
    price: 3499,
    originalPrice: 4999,
    rating: 4.5,
    reviews: 12456,
    emoji: '🏸',
    badge: 'sale',
    engravable: false,
    img: 'https://m.media-amazon.com/images/I/51GqgRlp1eL._AC_SX522_.jpg',
    backImg: '',
    imgs: ['https://m.media-amazon.com/images/I/51GqgRlp1eL._AC_SX522_.jpg'],
    desc: 'Astrox series with rotational generator system for steep attacking play.',
    features: ['Namd flex carbon', 'Energy optimum frame', 'T-Anchor system', 'Even balance'],
    specs: {
      Weight: '85g',
      Balance: 'Even',
      Flex: 'Stiff',
      String: 'Pre-strung',
    },
  },
  {
    id: 22,
    name: "L'Oréal Revitalift Serum",
    brand: "L'Oréal",
    category: 'Beauty',
    price: 899,
    originalPrice: 1299,
    rating: 4.4,
    reviews: 28765,
    emoji: '🧴',
    badge: 'sale',
    engravable: false,
    img: 'https://m.media-amazon.com/images/I/51m8DfG-E+L._AC_SX522_.jpg',
    backImg: '',
    imgs: ['https://m.media-amazon.com/images/I/51m8DfG-E+L._AC_SX522_.jpg'],
    desc: 'Pure 1.5% Hyaluronic Acid serum. Clinically proven to reduce wrinkles.',
    features: ['1.5% Pure Hyaluronic Acid', '3 types of HA', 'Clinically tested', 'Fragrance-free'],
    specs: {
      Volume: '30ml',
      Type: 'Serum',
      'Skin Type': 'All',
      SPF: 'None',
    },
  },
  {
    id: 23,
    name: 'Maybelline Fit Me Foundation',
    brand: 'Maybelline',
    category: 'Beauty',
    price: 399,
    originalPrice: 699,
    rating: 4.3,
    reviews: 54321,
    emoji: '🫧',
    badge: 'sale',
    engravable: false,
    img: 'https://m.media-amazon.com/images/I/61ZSEhzPfkL._AC_SX522_.jpg',
    backImg: '',
    imgs: ['https://m.media-amazon.com/images/I/61ZSEhzPfkL._AC_SX522_.jpg'],
    desc: 'Fits your skin tone. Natural matte finish that does not clog pores.',
    features: ['40+ shades', 'Matte + Poreless finish', 'Dermatologist tested', 'SPF 18'],
    specs: {
      Volume: '30ml',
      Finish: 'Matte',
      SPF: '18',
      Suitable: 'Normal to Oily',
    },
  },
  {
    id: 24,
    name: 'LEGO Technic Bugatti Chiron',
    brand: 'LEGO',
    category: 'Toys',
    price: 14999,
    originalPrice: 17999,
    rating: 4.8,
    reviews: 3421,
    emoji: '🏎️',
    badge: 'new',
    engravable: false,
    img: 'https://m.media-amazon.com/images/I/91TNQvqvmqL._AC_SX522_.jpg',
    backImg: '',
    imgs: ['https://m.media-amazon.com/images/I/91TNQvqvmqL._AC_SX522_.jpg'],
    desc: 'Build and display the iconic Bugatti Chiron in 1:8 scale with 3,599 pieces.',
    features: ['3,599 pieces', '1:8 scale', 'Working W16 engine', 'Functioning gearbox'],
    specs: {
      Pieces: '3599',
      Scale: '1:8',
      Age: '16+',
      Theme: 'Technic',
    },
  },
  {
    id: 25,
    name: 'Hot Wheels 20-Car Gift Pack',
    brand: 'Hot Wheels',
    category: 'Toys',
    price: 699,
    originalPrice: 999,
    rating: 4.6,
    reviews: 45678,
    emoji: '🚗',
    badge: 'sale',
    engravable: false,
    img: 'https://m.media-amazon.com/images/I/81r5JxP9o3L._AC_SX522_.jpg',
    backImg: '',
    imgs: ['https://m.media-amazon.com/images/I/81r5JxP9o3L._AC_SX522_.jpg'],
    desc: '20 Hot Wheels die-cast vehicles, 1:64 scale. Great starter set.',
    features: ['20 vehicles', '1:64 scale die-cast', 'Multiple styles', 'Collectible'],
    specs: {
      Scale: '1:64',
      Count: '20 cars',
      Age: '3+',
      Material: 'Die-cast Metal',
    },
  },
  {
    id: 26,
    name: 'Himalayan Pink Salt Lamp',
    brand: 'Amber',
    category: 'Garden',
    price: 799,
    originalPrice: 1499,
    rating: 4.1,
    reviews: 32145,
    emoji: '🏮',
    badge: 'sale',
    engravable: false,
    img: 'https://m.media-amazon.com/images/I/71F9IpEWR6L._AC_SX522_.jpg',
    backImg: '',
    imgs: ['https://m.media-amazon.com/images/I/71F9IpEWR6L._AC_SX522_.jpg'],
    desc: '100% authentic Himalayan rock salt lamp. Air purify naturally.',
    features: ['100% authentic salt', 'Dimmer switch', 'Wooden base', '15W bulb included'],
    specs: {
      Weight: '2-4 kg',
      Bulb: '15W',
      Base: 'Wooden',
      Size: '6-8 inch',
    },
  },
];
